myblog/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    url(r'^index/$', views.index, name = 'index'),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action,name='edit_action'),
    url(r'^uploadImg/$', views.uploadImg),
    url(r'^showImg/$', views.showImg, name = 'showImg'),

    #登录
    url(r'^denglu/$',views.denglu,name = 'denglu'),
    #退出
    url(r'^dengchu/$',views.dengchu,name = 'dengchu'),
    #注册
    url(r'^zhuce/$',views.zhuce, name =  'zhuce'),
    #个人中心
    url(r'^user_center/$',views.user_center, name = 'user_center'),
    #编辑个人信息
    url(r'^user_center/edit_profile/$',views.edit_profile, name = 'edit_profile'),
    #修改密码
    url(r'^user_center/change_password/$',views.change_password, name = 'change_password'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^captcha/', include('captcha.urls')),
]

myblog/blog/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class vipone (models.Model):
    comvip = models.OneToOneField(User, on_delete = models.CASCADE)
    nicheng = models.CharField(blank = True, max_length=50)
    birthday = models.DateField(blank = True)

    class Meta:
        verbose_name_plural = 'vipone'


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __unicode__(self):
        return self . title

class Img(models.Model):
    img_url = models.ImageField(upload_to = 'img')

myblog/blog/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
#验证码
from captcha.fields import CaptchaField


# 自定义编辑表单，继承原来的表单UserChangeForm
class zidingyiEditForm(UserChangeForm):
    nicheng = forms.CharField(required=False, max_length=50)
    birthday = forms.CharField(required=False)

    class Meta:
        model = User
		#显示什么是可以被编辑的
        fields = ('username', 'password', 'email', 'nicheng', 'birthday')

    # 初始化的构造函数
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique': '用户名已存在！！！！ ', 'invalid': '格式不正确！！！'}


# 自定义注册表单，继承原来的表单
class zidingyiForm(UserCreationForm):
    nicheng = forms.CharField(required=False, max_length=50)
    birthday = forms.CharField(required=False)
    captcha = CaptchaField()
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'nicheng', 'birthday')

    # 初始化的构造函数
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique': '用户名已存在！！！！ '}

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .import models
from django.contrib.auth.decorators import login_required

#登录
from django.contrib.auth import authenticate, login, logout
#注册 UserCreationForm     修改信息UserChangeForm     修改密码PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm,UserChangeForm, PasswordChangeForm
from .forms import zidingyiForm,zidingyiEditForm
from .models import vipone

#个人中心
@login_required(login_url='blog:denglu')
def user_center(request):
    yonghuInfo = {'yonghuInfo': request.user}
    return render(request,'users/user_center.html',yonghuInfo)

#编辑个人信息
@login_required(login_url='blog:denglu')
def edit_profile(request):
    if request.method == 'POST':
        editForm = zidingyiEditForm(request.POST,instance=request.user,)  # 实例化创建一个表单
        if editForm.is_valid():
            editForm.save()
            request.user.vipone.nicheng = editForm.cleaned_data['nicheng']
            request.user.vipone.birthday = editForm.cleaned_data['birthday']
            request.user.vipone.save()
            # vipone(comvip=user, nicheng=regForm.cleaned_data['nicheng'],
            #        birthday=regForm.cleaned_data['birthday']).save()
            return redirect('blog:user_center')
    else:
        editForm = zidingyiEditForm(instance = request.user)  # 实例化创建一个表单
    return render(request, 'users/edit_profile.html', {'editForm': editForm,'user':request.user})


#修改密码
@login_required(login_url='blog:denglu')
def change_password(request):
    if request.method == 'POST':
        editPassword = PasswordChangeForm(data = request.POST,user=request.user, )  # 实例化创建一个表单
        if editPassword.is_valid():
            editPassword.save()
            return redirect('blog:denglu')
    else:
        editPassword = PasswordChangeForm(user=request.user)  # 实例化创建一个表单
    return render(request, 'users/change_password.html', {'editPassword': editPassword, 'user': request.user})


#注册
def zhuce(request):
    if request.method == 'POST':
        regForm = zidingyiForm(request.POST)
        if regForm.is_valid():
            regForm.save()
            user = authenticate(username=regForm.cleaned_data['username'], password=regForm.cleaned_data['password1'])
            user.email = regForm.cleaned_data['email']
            vipone(comvip=user,nicheng=regForm.cleaned_data['nicheng'],birthday = regForm.cleaned_data['birthday']).save()
            login(request, user)
            return redirect('blog:index')
    else:
        regForm = zidingyiForm()   #实例化创建一个表单
    return render(request,'users/register.html', {'reg':regForm})


#登录
def denglu(request):
    if request.method == 'POST':
       user = authenticate(request,username=request.POST['用户名'],password=request.POST['密码'])
       if user is None:
            return render(request,'users/login.html',{'错误':'用户名不存在'})
       else:
           login(request,user)
           return redirect('blog:index')

    else:
        return render(request,'users/login.html')

#登出
def dengchu(request):
    logout(request)
    return redirect('blog:index')

def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})

def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id',0)
    if article_id == '0':
        models.Article.objects.create(title=title,content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})

    article = models.Article.objects.get(pk=article_id)
    article.title=title
    article.content=content
    article.save()
    return render(request, 'blog/article_page.html', {'article':article})


def uploadImg(request):#图片上传函数
    if request.method == 'POST':
        img = models.Img(img_url=request.FILES.get('img'))
        img.save()
    return render(request,'blog/imgUpload.html')

def showImg(request):#图片显示函数
    imgs = models.Img.objects.all()  # 从数据库中取出所有的图片路径
    context = {
        'imgs': imgs
    }
    return render(request, 'blog/showImg.html', context)

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_psge</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}"/>
        </label>
        <br/>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}"/>
        </label>
        <br/>
        <br/>
    <input type="submit" value="提交">
</form>

</body>
</html>

myblog/blog/templates/blog/imgUpload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="img">
    <input type="submit" value="上传">
</form>


<br><br>

<a href="{% url 'blog:showImg' %}">显示图片</a>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user.is_authenticated %}
        <h1><a href="{% url 'blog:dengchu' %}">登出</a></h1>
        <h1><a href="{% url 'blog:user_center' %}">个人中心</a></h1>
    {% else %}
        <h1><a href="{% url 'blog:denglu' %}">登录</a></h1>
        <h1><a href="{% url 'blog:zhuce' %}">注册</a></h1>
    {% endif %}


    <h1>
        <a href="{% url 'blog:edit_page' 0%}">新文章</a>
    </h1>
    {% for article in articles %}
        <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
        <br/>
    {% endfor %}
</body>
</html>

myblog/blog/templates/blog/showImg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 {% for item in imgs %}
        <img src="..{{ item.img_url.url }}"><br/>
    {% endfor %}
</body>
</html>

myblog/blog/templates/users/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:index' %}">回到主页</a></h1>
<h1><a href="{% url 'blog:user_center' %}">个人中心</a></h1>
<h1><a href="{% url 'blog:edit_profile' %}">编辑个人信息</a></h1>
<h1><a href="{% url 'blog:change_password' %}">修改密码</a></h1>
<h1><a href="{% url 'blog:dengchu' %}">登出</a></h1>
{{ editPassword.errors }}
<form action="" method="POST">
    {% csrf_token %}
    <form action="" method="POST">
        <p>
            <label for="id_old_password">旧密码:</label>
            <input type="password" name="old_password" autofocus required
                                                            id="id_old_password">
        </p>
        <p>
            <label for="id_new_password1">新密码:</label>
            <input type="password" name="new_password1" required
                                                             id="id_new_password1">
            <span class="helptext">
                <ul>
                    <li>你的密码不能与其他个人信息太相似。</li>
                    <li>你的密码必须包含至少 8 个字符。</li>
                    <li>你的密码不能是大家都爱用的常见密码。</li>
                    <li>你的密码不能全部为数字。</li>
                </ul>
            </span>
        </p>
        <p>
            <label for="id_new_password2">新密码确认:</label>
            <input type="password" name="new_password2" required
                                                               id="id_new_password2">
        </p>
        <button type="submit">提交</button>
    </form>
</form>
</body>
</html>

myblog/blog/templates/users/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:index' %}">回到主页</a></h1>
<h1><a href="{% url 'blog:user_center' %}">个人中心</a></h1>
<h1><a href="{% url 'blog:edit_profile' %}">编辑个人信息</a></h1>
<h1><a href="{% url 'blog:change_password' %}">修改密码</a></h1>
<h1><a href="{% url 'blog:dengchu' %}">登出</a></h1>
{{ editForm.errors }}
<form action="" method="POST">
    {% csrf_token %}
    <p>
        <label for="id_username">用户名:</label>
        <input type="text" name="username" value="{{ user.username }}" maxlength="150" required
                                                    id="id_username">
        <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>
    </p>
    <p>
        <label for="id_email">电子邮件地址:</label>
        <input type="email" name="email" value="{{ user.email }}" maxlength="254"
                                                    id="id_email">
    </p>
    <p>
        <label for="id_nicheng">Nicheng:</label>
        <input type="text" name="nicheng" maxlength="50" id="id_nicheng" value="{{ user.vipone.nicheng }}">
    </p>
    <p>
        <label for="id_birthday">Birthday:</label>
        <input type="date" name="birthday" id="id_birthday" value="{{ user.vipone.birthday }}">
    </p>
    <button type="submit">提交</button>
</form>
</body>
</html>

myblog/blog/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1><a href="{% url 'blog:index' %}">回到主页</a> </h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ 错误 }}
        <input type="text" name="用户名" placeholder="用户名"/>
        <input type="password" name="密码" placeholder="密码"/>
        <button type="submit">登录</button>
    </form>
</body>
</html>

myblog/blog/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>
<body>
<h1>注册</h1>
<h1><a href="{% url 'blog:index' %}">回到主页</a></h1>

{# action   当前本页的网址#}
<form action="" method="POST">

{% csrf_token %}
    <p>
        <label for="id_username">用户名:</label>
        <input type="text" name="username" maxlength="150" autofocus required
               id="id_username">
        <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>
    </p>
        {%  if reg.errors.username %}
            <p>用户名已存在</p>
            {{ reg.errors.username }}
        {% endif %}
    <p>
        <label for="id_password1">密码:</label>
        <input type="password" name="password1" required id="id_password1">
        <span class="helptext">
            <ul>
                <li>你的密码不能与其他个人信息太相似。</li>
                <li>你的密码必须包含至少 8 个字符。</li>
                <li>你的密码不能是大家都爱用的常见密码。</li>
                <li>你的密码不能全部为数字。</li>
            </ul>
        </span>
    </p>
    <p>{{ reg.errors.password1 }}</p>
    <p><label for="id_password2">密码确认:</label>
        <input type="password" name="password2" required id="id_password2">
        <span class="helptext">为了校验，请输入与上面相同的密码。</span>
    </p>
    <p>{{ reg.errors.password2 }}</p>
    <p>
        <label for="id_email">电子邮件地址:</label>
        <input type="email" name="email" maxlength="254" id="id_email">
    </p>
    <p>{{ reg.errors.email }}</p>
    <p>
        <label for="id_nicheng">昵称:</label>
        <input type="text" name="nicheng" maxlength="50" id="id_nicheng">
    </p>
    <p>{{ reg.errors.nicheng }}</p>
    <p>
        <label for="id_birthday">生日:</label>
        <input type=date name="birthday" id="id_birthday">
    </p>
    <p>{{ reg.errors.birthday }}</p>
    <p>{{ reg.captcha}}</p>
    <p>{{ reg.errors.captcha}}</p>
    <button type="submit">注册</button>
</form>


</body>

<script type="text/javascript">
    $('.captcha').click(function(){
        console.log('click');
         $.getJSON("/captcha/refresh/",
                  function(result){
             $('.captcha').attr('src', result['image_url']);
             $('#id_captcha_0').val(result['key'])
          });
});

</script>
</html>

myblog/blog/templates/users/user_center.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h1><a href="{% url 'blog:index' %}">回到主页</a></h1>
        <h1><a href="{% url 'blog:edit_profile' %}">编辑个人信息</a></h1>
        <h1><a href="{% url 'blog:change_password' %}">修改密码</a></h1>
        <h1><a href="{% url 'blog:dengchu' %}">登出</a></h1>

        <div>
            <p>用户名：{{ yonghuInfo.username }}</p><br>
            <p>邮箱：{{ yonghuInfo.email }}</p><br>
            <p>生日：{{ yonghuInfo.vipone.birthday }}</p><br>
            <p>昵称：{{ yonghuInfo.vipone.nicheng }}</p><br>
        </div>

</body>
</html>